name: Debug CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap wget unzip python3-pip golang-go

      - name: Install Sublist3r
        run: |
          git clone https://github.com/aboul3la/Sublist3r.git
          cd Sublist3r
          pip3 install -r requirements.txt
          sudo ln -s $(pwd)/sublist3r.py /usr/local/bin/sublist3r
          cd ..

      - name: Install Amass
        run: |
          wget https://github.com/owasp-amass/amass/releases/download/v3.26.0/amass_linux_amd64.zip
          unzip amass_linux_amd64.zip
          sudo mv amass_linux_amd64/amass /usr/local/bin/
          amass -h

      - name: Install Subfinder
        run: |
          go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          sudo ln -s ~/go/bin/subfinder /usr/local/bin/subfinder

      - name: Test Installations
        run: |
          sublist3r -h
          amass -h
          subfinder -h
