name: Enhanced Reconnaissance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  recon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y nmap  # Install Nmap directly

          # Install Sublist3r
          git clone https://github.com/aboul3la/Sublist3r.git
          cd Sublist3r
          pip install -r requirements.txt
          sudo ln -s $(pwd)/sublist3r.py /usr/local/bin/sublist3r
          cd ..

          # Install Amass
          wget https://github.com/owasp-amass/amass/releases/download/v3.25.3/amass_linux_amd64.zip
          unzip amass_linux_amd64.zip
          sudo mv amass_linux_amd64/amass /usr/local/bin/

          # Install Subfinder
          GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
          sudo ln -s ~/go/bin/subfinder /usr/local/bin/subfinder

      - name: Run Sublist3r
        run: |
          sublist3r -d linkedin.com -o sublist3r_results.txt

      - name: Run Amass
        run: |
          amass enum -d linkedin.com -o amass_results.txt

      - name: Run Subfinder
        run: |
          subfinder -d linkedin.com -o subfinder_results.txt

      - name: Combine results
        run: |
          cat sublist3r_results.txt amass_results.txt subfinder_results.txt | sort -u > combined_subdomains.txt

      - name: Run Nmap
        run: |
          nmap -iL combined_subdomains.txt -p 1-1000 -sV -oN nmap_results.txt

      - name: Generate Reports
        run: |
          python3 generate_report.py combined_subdomains.txt subdomain_report.txt
          python3 generate_report.py nmap_results.txt nmap_report.txt

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: recon-results
          path: |
            subdomain_report.txt
            nmap_report.txt

      - name: Notify on results
        run: |
          echo -e "Subject: Recon Results\n\nSubdomain and Nmap scan results have been generated. Check the attached reports." | mail -s "Recon Results" -A subdomain_report.txt -A nmap_report.txt internetcafedzk@gmail.com
