name: Subjack Cron Job

on:
  schedule:
    # Run every day at midnight
    - cron: "0 0 * * *"

jobs:
  run-subjack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install subjack

    - name: Run Subjack
      run: |
        subjack -w cleaned_linksubs.txt -t 100 -timeout 30 -ssl -o cronjobtkovr.txt

    - name: Check for Vulnerabilities
      run: |
        if grep -q "Vulnerable" cronjobtkovr.txt; then
          echo "Subjack found potential takeovers!"
        else
          echo "No vulnerabilities found."
        fi
